#!/bin/sh

# Set these paths appropriately

BIN=/Users/Amine/Downloads/bin
CMD=/Users/Amine/Downloads/cmd
LIB=/Users/Amine/Downloads/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian-utf8.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
