#!/bin/sh

# Set these paths appropriately

BIN=/Users/Amine/Downloads/bin
CMD=/Users/Amine/Downloads/cmd
LIB=/Users/Amine/Downloads/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
