#!/bin/sh

# Set these paths appropriately

BIN=/Users/Amine/Downloads/bin
CMD=/Users/Amine/Downloads/cmd
LIB=/Users/Amine/Downloads/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
