#!/bin/sh

# Set these paths appropriately

BIN=/Users/Amine/Downloads/bin
CMD=/Users/Amine/Downloads/cmd
LIB=/Users/Amine/Downloads/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
